apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-y0k7
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-43256-0026-tenant/ci1t-43256-0026-app/devfile-sample-y0k7@sha256:e60259f02030afdc7d4132b77b6b4290b6fc0f8f62b3424bd51470eb8d2b9152
        name: my-nodejs
        resources: {}
status: {}
